INSERT INTO "QUESTIONS" ("Category", "Question", "Answer") VALUES
('Video Games', 'What game made popular the phrase "Do a barrel roll?"', 'Star Fox 64'),
('Video Games', 'Who is the main character from Final Fantasy VII', 'Cloud Strife'),
('Video Games', 'What is Mario''s surname', 'Mario'),
('Video Games', 'What was Mario''s original name', 'Jumpman'),
('Video Games', 'In what game did Mario make his first appearance', 'Donkey Kong'),
('Video Games', 'Who was Sega''s mascot', 'Sonic the Hedgehog'),
('Video Games', 'Who is the main character of Final Fantasy VIII', 'Squall Lionheart'),
('Video Games', 'What game mixed both Disney characters with Final Fantasy characters', 'Kingdom Hearts'),
('Video Games', 'Who is the main character in Kingdom Hearts', 'Sora'),
('Video Games', 'In the original Kingdom Hearts, who is Sora looking for', 'Kairi'),
('Video Games', 'Who is the main character from Final Fantasy IX', 'Zidane Tribal'),
('Video Games', 'In what series of video games did Master Chief appear', 'Halo'),
('Video Games', 'What video game made the Golden Gun famous', 'Goldeneye'),
('Computers', 'The generic term for the mechanical, electrical and electronic components of a computer are called what', 'Hardware'),
('Computers', 'Which computer language is an acronym of the name of the world''s first computer programmer', 'ADA'),
('Computers', 'What letter is between Q and E on a computer keyboard', 'W'),
('Computers', 'In computer lingo what is a MUD', 'Multi User Computer Game'),
('Computers', 'What kind of fruit was used to name a computer in 1984', 'Apple'),
('Computers', 'In what field of study are the terms CPU, PC, and VDU used', 'Computer Science'),
('Computers', 'From what source did William Henry Gates III amass his fortune', 'Computer software'),
('Computers', 'Charlie the pet dog was replace by what in the remake of the Absent-minded Professor called "Flubber" in 1997', 'Weebo, the computer'),
('Computers', 'What did Charles Babbage invent when he designed his analytical engine in 1833', 'Computer'),
('Computers', 'Movie maker George Lucas Filed a law suit against President Ronald Reagan to get him to stop referring to an outer space computer controlled defense system as what', 'Star Wars'),
('Computers', 'What time doe the computer virus W32.MARIJUANA interrupt you to suggest taking a break', '4:20 p.m.'),
('Computers', 'Hal, the computer in 2001: A Space Odyssey, got its name how', 'The letters before I B and M'),
('Computers', 'Pixar created a 1995 blockbuster hit move using computer animation. What was the title of the movie', 'Toy Story'),
('Computers', 'Which computer company dropped the Play Station line and created an Aptiva brand computer for home users', 'IBM corporation'),
('Computers', 'Red Hat and Yellow Dog are computer outfits that distributed an alternative computer operating system. What was the name of the system', 'Linux'),
('Computers', 'The Electronic Frontier Foundation named its $250,000 computer designed to crack the U.S. government''s outdated DES cryptographic code what', 'Deep Crack'),
('Computers', 'What common element is used in the manufacture of computer chips', 'Silicon'),
('Computers', 'On the birthday of a famous painter, every March 6th, what computer virus strikes', 'Michelangelo'),
('Computers', 'The Dancing Baby computer generated 3D image danced it''s way onto what TV show in 1998', 'Ally McBeal'),
('Computers', 'What U.S. Democratic senator had the first internet home page', 'Ted Kennedy'),
('Computers', 'Originally, ENIAC, the world''s first "modern" computer was constructed to do what', 'To compute ballistic trajectories for artillery shells'),
('Computers', 'The Los Angeles Police Department developed a computer program to help solve homicides. What was it called', 'HITMAN'),
('Computers', 'The first computer used for weather research was named what', 'MANIAC'),
('Computers', 'The displays commonly found in notebook and laptop computers are called what', 'Liquid Crystal Display'),
('Computers', 'After breaking into physicist Tsutomu Shimomura''s computer on Christmas in 1994, what legendary hacker was taken down', 'Kevin Mitnick'),
('Computers', 'What personal computer became a video production system with the addition of New Tek''s Video Toaster', 'Amiga'),
('Computers', 'Digital Equipment Corporation sued what computer chip manufacturer claiming it stole the technology to develop the Pentium Pro', 'Intel Corporation'),
('Computers', 'What was the name of the computer language named after a French philosopher and mathematician', 'PASCAL'),
('Computers', 'What was the name of the computer company that was named after the founder''s memories of a summer in an Orchard in Oregon', 'Apple'),
('Science', 'What is Deoxyribonucleic acid commonly referred to as?', 'DNA'),
('Science', 'What is Ribonucleic acid commonly referred to as?', 'RNA'),
('Science', 'What process involves treating rubber with sulfur to harden it?', 'Vulcanizing'),
('Science', 'What scale of zero to 14 is used to measure acidity or alkalinity?', 'The pH scale'),
('Science', 'What O-word describes oxygen with molecules that have three atoms instead of two?', 'Ozone'),
('Science', 'What unit of electrical power is equal to one joule per second?', 'The Watt'),
('Science', 'What planet is closest in size to our moon?', 'Mercury'),
('Science', 'What''s the common name for a cubic decimeter?', 'liter'),
('Science', 'What measure of energy comes from the Latin word meaning "heat"?', 'The calorie'),
('Science', 'What''s removed from water in the process of desalination?', 'Salt'),
('Science', 'What species Amazonian electric variety packs a 650 volt wallop?', 'The eel'),
('Science', 'What C word defines a substance that speeds a chemical reaction without being consumed?', 'Catalyst'),
('Science', 'What''s the base unit of mass in the metric system?', 'The kilogram'),
('Science', 'What cooking fuel is produced by heating wood without oxygen?', 'Charcoal'),
('Science', 'What''s the only metal that''s not a solid at room temperature?', 'Mercury'),
('Science', 'Which will yield the most BTUs of energy--a gallon of oil, a pound of coal or a gallon of gasoline?', 'A gallon of oil'),
('Science', 'What unit of measure do you multiply by .39 to convert it to inches?', 'Centimeters'),
('Science', 'What method of underwater detection is short for "sound navigation and ranging"?', 'Sonar'),
('Science', 'What hazardous substance is euphemistically referred to as "mineral fiber"?', 'Asbestos'),
('Science', 'What color does litmus turn when dipped into acid?', 'Pink'),
('Science', 'What process involves heating an ore to obtain a metal?', 'Smelting'),
('Science', 'What''s the U. S. equivalent of 0.45 kilograms?', 'One pound'),
('Science', 'What''s defined as the distance between a lens and its focal point?', 'Focal Length'),
('Science', 'What energy unit is defined as the heat required to raise one kilogram of water by one degree Celsius?', 'One Calorie'),
('Science', 'What founding father was knocked unconscious while attempting to electrocute a turkey?', 'Benjamin Franklin'),
('Science', 'What continent is subjected to the world''s largest ozone hole?', 'Antarctica'),
('Science', 'What sea creature can have an eye measuring 16 inches across, the largest in the animal kingdom?', 'A squid'),
('Science', 'What explosive cosmic event was seen with the naked eye in 1987, for the first time in 383 years?', 'A supernova'),
('Science', 'What three terms are represented in Newton''s second law of motion F = ma?', 'Force, mass, acceleration'),
('Science', 'How many of the nine planets have moons?', 'Seven'),
('Science', 'What were exterminated from Harvard''s bio labs when they were found to be carrying radioactive chemicals into the walls?', 'Ants'),
('Science', 'What type of trees yield the resin used to produce turpentine?', 'Pine trees'),
('Science', 'What''s the most malleable metal?', 'Gold'),
('Science', 'When drawing circles what instrument would you use?', 'Compass'),
('Science', 'What does a meteorologist study?', 'Weather'),
('Science', 'The chinese invented this black powder to make fireworks?', 'Gunpowder'),
('Science', 'This word describes the force that pulls objects to the middle of the earth?', 'Gravity'),
('Science', 'What has a face, hands and wheels?', 'Clock'),
('Science', 'Nephrology is the study of which organs?', 'Kidneys'),
('Science', 'Where in the human body would you find the scaphoid bone?', 'Wrist'),
('Science', 'From the bark of which tree was aspirin originally obtained?', 'Willow'),
('Science', 'What is Acetic Acid more commonly known as?', 'Vinegar'),
('Science', 'Cumulus and Cirrus are types of what?', 'Clouds'),
('Science', 'Which grow upwards Stalactites or Stalagmites?', 'Stalagmites'),
('Science', 'What can be Forked, Sheet or ball?', 'Lightning'),
('Science', 'When Litmus paper is in contact with Alkaline what colour does it become?', 'Blue'),
('Science', 'The best conductor of electricity is which metal?', 'Silver'),
('Science', 'The curved line between any two points on a circle is referred to as what?', 'An arc'),
('Science', 'Cumulus and Cirrus are types of what?', 'Cloud'),
('Science', 'Calcium Carbonate is more commonly known as what?', 'Chalk'),
('Science', 'Sugar found in fruit is known by what name?', 'Fructose'),
('Science', 'This metal is liquid at room temperature?', 'Mercury'),
('Science', 'The most sensitive of the senses is what?', 'Smell'),
('Science', 'These creatures were used to bleed patients in the nineteeth century?', 'Leeches'),
('Science', 'Acid turns Litmus paper which colour?', 'Red'),
('Science', 'This is the most common element in the universe?', 'Hydrogen '),
('Food', 'What milk product did the U.S. Agriculture Department propose as a substitute for meat in school lunches, in 1996?', 'Yogurt'),
('Food', 'What breakfast cereal was Sonny the Cuckoo Bird "cuckoo for"?', 'Cocoa Puffs'),
('Food', 'On what vegetable did an ancient Egyptian place his right hand when taking an oath?', 'The onion'),
('Food', 'How many flowers are in the design stamped on each side of an Oreo cookie?', 'Twelve'),
('Food', 'Black-eyed peas are not peas. What are they?', 'Beans'),
('Food', 'Under what name did the Domino''s Pizza chain get its start?', 'DomNick''s'),
('Food', 'What was margarine called when it was first marketed in England?', 'Butterine'),
('Food', 'What are the two top selling spices in the world?', 'Pepper and mustard'),
('Food', 'What was the name of Cheerios when it was first marketed 50 years ago?', 'Cheerioats'),
('Food', 'What flavor of ice cream did Baskin-Robbins introduce to commemorate America''s landing on the moon on July 20, 1969?', 'Lunar Cheesecake'),
('Food', 'What is the most widely eaten fish in the world?', 'The Herring'),
('Food', 'What is the name of the evergreen shrub from which we get capers?', 'The caper bush'),
('Food', 'What animals milk is used to make authentic Italian mozzarella cheese?', 'The water buffalo''s'),
('Food', 'What nation produces two thirds of the world''s vanilla?', 'Madagascar'),
('Food', 'What was the drink we know as the Bloody Mary originally called?', 'The Red Snapper'),
('Food', 'What was the first commercially manufactured breakfast cereal?', 'Shredded Wheat'),
('Food', 'When Birdseye introduced the first frozen food in 1930, what did the company call it?', 'Frosted Food'),
('Food', 'What American city produces most of the egg rolls sold in grocery stores in the United States?', 'Houston, Texas'),
('Food', 'What was the first of H.J. Heinz'' "57 varieties"?', 'Horseradish'),
('Food', 'What is the literal meaning of the Italian word linguine?', 'Little tongues'),
('Food', 'Where did the pineapple plant originate?', 'South America'),
('Food', 'What recipe, first published 50 years ago, has been requested most frequently through the years by the readers of "Better Homes and Garden"?', 'Hamburger Pie'),
('Food', 'What is the only essential vitamin not found in the white potato?', 'Vitamin A'),
('Food', 'What food is the leading source of salmonella poisoning?', 'Chicken'),
('Food', 'What company first condensed soup in 1898?', 'Campbell''s'),
('Food', 'What nutty legume accounts for one sixth of the world''s vegetable oil production?', 'The peanut'),
('Food', 'What country saw the cultivation of the first potato, in 200 A.D.?', 'South America'),
('Food', 'What type of lettuce was called Crisphead until the 1920s?', 'Iceberg lettuce'),
('Food', 'What tree gives us prunes?', 'The plum tree'),
('Food', 'What type of chocolate was first developed for public consumption in Vevey, Switzerland in 1875?', 'Milk Chocolate'),
('Food', 'What added ingredient keeps confectioners'' sugar from clumping?', 'Corn starch'),
('Food', 'What edible comes in crimmini, morel, oyster and wood ear varieties?', 'Mushrooms'),
('Food', 'What newly-imported substance caused the first major outbreak of tooth decay in Europe, in the1500''s?', 'Sugar'),
('Food', 'What ingredient in fresh milk is eventually devoured by bacteria, causing the sour taste?', 'Lactose'),
('Food', 'What uncooked meat is a trichina worm most likely to make a home in?', 'Pork'),
('Food', 'What baking ingredient, sprayed at high pressure, did the U.S. Air Force replace its toxic paint stripper with?', 'Baking soda'),
('Food', 'What staple is laced with up to 16 additives including plaster of paris, to stay fresh?', 'Bread'),
('Food', 'What falling fruit supposedly inspired Isaac Newton to write the laws of gravity?', 'An Apple'),
('Food', 'What method of preserving food did the Incas first use, on potatoes?', 'Freeze-drying'),
('Food', 'What drupaceous fruit were Hawaiian women once forbidden by law to eat?', 'The coconut'),
('Food', 'What hit the market alongside spinach as the first frozen veggies?', 'Peas'),
('Food', 'How many sizes of chicken eggs does the USDA recognize, including peewee?', 'Six'),
('Food', 'What are de-headed, de-veined an sorted by size in a laitram machine?', 'Shrimp'),
('Food', 'What''s the only fish that produces real caviar, according to the FDA?', 'Sturgeon'),
('Food', 'What type of egg will yield 11 and one-half average-size omelettes?', 'An Ostrich egg'),
('Food', 'What sticky sweetener was traditionally used as an antiseptic ointment for cuts and burns?', 'Honey'),
('Food', 'What should your diet be high in to lessen the chance of colon cancer, according to a 1990 study?', 'Fiber'),
('Food', 'What nut do two-thirds of its U. S. producers sell through Blue Diamond?', 'The Almond'),
('Food', 'What type of oven will not brown foods?', 'Microwave oven'),
('Food', 'What type of food did Linda McCartney launch?', 'Vegetarian food'),
('Food', 'What type of tree leaves are the only food that a koala bear will eat?', 'Eucalyptus'),
('Food', 'Which country in Europe consumes more spicy Mexican food than any other?', 'Norway'),
('Food', 'The FDA approved what fat substitute for use in snack foods even though there were reports of side affects like cramps and diarrhea?', 'Olestra'),
('Food', 'Federal labeling regulations require how much caffeine be removed from coffee for it to be called decaffeinated?', 'Ninety seven percent'),
('Food', 'What famous Greek once advised: "Let your food be your medicine, and your medicine be your food"?', 'Hippocrates'),
('Food', 'Chicken is the leading cause of what food born illness?', 'Salmonella poisoning'),
('Food', 'Who invented Margarine in 1868?', 'Hyppolyte Merge-mouries'),
('Food', 'What group of people were the first to use freeze-drying on potatoes?', 'The Incas'),
('Food', 'What was the Teenage Mutant Ninja Turtles favorite food?', 'Pizza'),
('Food', 'What food was considered the food of the Gods, and was said to bring eternal life to anyone who ate it?', 'Ambrosia'),
('Food', 'What was the convenience food that Joel Cheek developed?', 'Instant Coffee'),
('Food', 'The song, Food, Glorious Food, was featured in which musical?', 'Oliver'),
('Food', 'Of the Worlds food crops, what percentage is pollinated by insects?', '80 percent'),
('Food', 'The Giant panda''s favorite food is what?', 'Bamboo shoots'),
('Food', 'Which entertainer on Conan O''Brien''s show, choose NBC cafeteria chicken over his own brand in a blind taste test?', 'Kenny Rogers'),
('Food', 'What drink was sold as Diastoid when first introduced?', 'Malted milk'),
('Food', 'What type of micro organism makes up the base of marine and freshwater food chains?', 'Plankton'),
('Food', 'What type of creature builds a lodge in which to store food, rear its young, and pass the winter?', 'Beaver'),
('Food', 'What fruit or vegetable was dubbed the FlavrSavr and was the first genetically engineered food sold in the United States?', 'The tomato'),
('Food', 'What fitness guru appeared as a dancing meatball in an Italian TV commercial as an art student?', 'Richard Simmons'),
('Food', 'What Olympic athlete could not run the 200-meter final in the 92 Olympics because of food poisoning?', 'Michael Johnson'),
('Food', 'What morning food has a name derived from the German word for stirrup?', 'Bagel'),
('Food', 'In 1904, what food product was renamed Post Toasties cereal because the clergy objected to the original name?', 'Elijah''s Manna'),
('Food', 'Which country does Rioja Wine come from?', 'Spain'),
('Food', 'The juice of which fruit will you find in a bloody mary?', 'Tomato'),
('Food', 'Homer Simpson drinks Which brand of beer regularly?', 'Duff'),
('Food', 'What is the main ingredient of paella?', 'Rice'),
('Food', 'What would you call a segment of garlic?', 'Clove'),
('Food', 'A canteloupe is what kind of fruit?', 'Melon'),
('Food', 'Sticky and sweet this food is produced in a hive?', 'Honey'),
('Food', 'This dairy product tastes good on crackers and sandwiches or on its own?', 'Cheese'),
('Food', 'In the dish of Beef Wellington, in what is the beef wrapped?', 'Pastry'),
('Food', 'What is The Teenage Mutant Ninja Turtles favourite food?', 'Pizza'),
('Food', 'What is the main vegetable ingredient in the dish Borsht?', 'Beetroot'),
('Food', 'Sauerkraut is pickled what?', 'Cabbage'),
('Food', 'What vegetable is also known as zucchini in the USA?', 'Courgette'),
('Food', 'This fruit goes into the liqueur Kirsch?', 'Cherry'),
('Food', 'A bloomer is what type of food?', 'Bread'),
('Food', 'Which is the fruit that contains the most calories?', 'Avocado pear'),
('Food', 'What is lava bread?', 'Seaweed'),
('Food', 'What fruit grows on the blackthorn tree?', 'Sloe'),
('Food', 'Which food has a name which means on a skewer?', 'Kebab'),
('Food', 'In a Mcdonald''s Big Mac how many pieces of bun are there?', 'Three'),
('Food', 'Oyster, Chestnut, or Shitaki are types of which vegetable?', 'Mushrooms'),
('Food', 'A Calzone Is A Folded Stuffed What?', 'Pizza'),
('Food', 'Which country invented the Marmite alternative - Veggie mite?', 'Australia'),
('Food', 'Which country does the dish Mousakka come from?', 'Greece'),
('Food', 'Which fruit served with cream is eaten during the summer tennis tournament Wimbledon?', 'Strawberries'),
('Food', 'Apart from potato What is the other main ingredient of Bubble and Squeak?', 'Cabbage'),
('Food', 'Which food was popular with Popeye the Sailor?', 'Spinach'),
('Food', 'What is Scooby Doo`s favourite food?', 'Scooby Snacks'),
('Food', 'What is the only fruit that grows its seeds on the outside?', 'Strawberry'),
('Food', 'What other names are sardines known by?', 'Pilchards'),
('Food', 'Which city gave its name to a three-coloured Neapolitan ice-cream?', 'Naples'),
('Food', 'What would you be drinking if you were drinking Earl Grey?', 'Tea'),
('Food', 'What are Pontefract cakes made from?', 'Liquorice'),
('Food', 'What is another name for almond paste?', 'Marzipan'),
('Food', 'What name can be a lettuce or a mass of floating frozen water?', 'Iceberg'),
('Food', 'What''s Sauerkraut''s main ingredient?', 'Cabbage'),
('Food', 'What''s the only rock edible to man?', 'Salt'),
('Food', 'What type of salad do you need apple, celery, walnuts, raisins and mayonnaise mixed together?', 'Waldorf Salad'),
('Food', 'Which fruit also shares its name with Gwyneth Paltrow''s daughter?', 'Apple'),
('Food', 'From which animal does haggis come?', 'Sheep'),
('Food', 'In cockney rhyming slang what is "Ruby Murray"?', 'Curry'),
('Food', 'What cake do you keep a layer of to eat at the christening of your first child?', 'Wedding Cake'),
('Food', 'Which brand of frozen ice cream cone was advertised to the tune of Italian song "O Sole Mio"?', 'Cornetto'),
('Food', 'If I take two apples out of a basket containing six apples how many apples do I have ?', 'Two'),
('Food', 'Which fruit does one of Bob Geldofs'' daughter share a name with?', 'Peaches'),
('Food', 'In Eggs Florentine which vegetable is a main ingredient?', 'Spinach'),
('Food', 'In a French restaurant what would you be eating if you chose escargots?', 'Snails'),
('Food', 'Which meat is usally in a Shish Kebab?', 'Lamb'),
('Food', 'What flavour is Ouzo?', 'Aniseed'),
('Food', 'A crapulous person is full of what?', 'Alcohol'),
('Food', 'What Italian Cheese usually tops a pizza?', 'Mozzarella'),
('Food', 'Port Salut is what?', 'Cheese'),
('Food', 'Who talked of eating human liver washed down with Chianti?', 'Hannibal Lecter'),
('Food', 'Who, according to the TV commercial, ‘makes exceedingly good cakes’?', 'Mr Kipling'),
('Food', 'What vegetable is sold mainly before 30th October?', 'Pumpkin'),
('Food', 'Whats the english translation for the french word crepe?', 'Pancake'),
('Food', 'What is a macadamia?', 'Nut'),
('Food', 'In ancient Egypt what was liquorice used for?', 'Medicine'),
('Food', 'What type of thin pancake is eaten in Mexico?', 'Tortilla'),
('Food', 'If steak was blue how would it be cooked?', 'Very Rare'),
('Food', 'Baked beans are made from which beans?', 'Haricot'),
('Food', 'What are small cubes of toasted or fried bread?', 'Croutons'),
('Food', 'What would you call a cluster of bananas?', 'A hand'),
('Food', 'What nuts are used to flavour amaretto?', 'Almonds'),
('Food', 'If you had frijoles refritos in a Mexican restaurant it would be refried what?', 'beans'),
('Food', 'This city is famous for its oranges?', 'Seville'),
('Food', 'Which celebrity chef was nicknamed ''The Naked Chef''?', 'Jamie Oliver'),
('Food', 'What daily vegetable do typical boxer''s ears look like?', 'Cauliflower'),
('Food', 'What''s a small pickled cucumber?', 'Gherkin'),
('Food', 'What''s cockney rhyming slang for eyes?', 'Mince Pies'),
('Food', 'What name''s given to a small, deep fried chinese dumpling with a savoury filing?', 'Won ton'),
('Food', 'Which brand of beer features a kangaroo on the packaging?', 'Fosters'),
('Food', 'A mint with a hole?', 'Polo'),
('Food', 'What is advertised on TV with the slogan "You either Love it or Hate it"?', 'Marmite'),
('Food', 'In Ancient China what variety of meat was reserved exclusively for the emperor?', 'Pork'),
('Food', 'Which song mentions saveloy, mustard, jelly, custard and sausages in the lyrics?', 'Food Glorious Food'),
('Food', 'Jasmine and long grain are both types of what?', 'Rice'),
('Food', 'What might you be eating at Wimbledon if you had a Cambridge Rival in your mouth?', 'Strawberry'),
('Food', 'What fruit was originally called a Chinese gooseberry?', 'Kiwi Fruit'),
('Food', 'What sort of pastry is used to make profiteroles?', 'Choux'),
('Food', 'What is the national dish of Hungary?', 'Goulash'),
('Food', 'Which nut is used to flavour traditional Bakewell Tart?', 'Almond'),
('Food', 'In the dish of Beef Wellington, in what is the beef wrapped?', 'Pastry'),
('Food', 'What is the main vegetable used to make Borsch?', 'Beetroot'),
('Food', 'What is Bombay Duck?', 'Fish'),
('Food', 'Which fruit is used in the making of a Black Forest Gateau?', 'Black Cherries'),
('Food', 'What is included in a BLT sandwich?', 'Bacon, lettuce and tomato'),
('Food', 'The name of what food, when translated, means twice-cooked?', 'Biscuit'),
('Food', 'How many calories are there in a stick of celery?', 'None'),
('Food', 'Which country consumes the most pasta per person per year?', 'Italy'),
('Food', 'What was the favourite food of Paddington Bear?', 'Marmalade'),
('Food', 'Which family of vegatables are Chives from?', 'Onions'),
('Food', 'In the Hansel and Gretel tale what was the wicked witch''s house made of?', 'Gingerbread'),
('Food', 'What take-away is traditional in England at the seaside?', 'Fish and chips'),
('Food', 'What meat is Coq au vin made with ?', 'Chicken'),
('Food', 'Which cheese is made in reverse?', 'Edam'),
('Food', 'What variety of banana shares its name with the title of a Bond movie?', 'Goldfinger'),
('Food', 'Conference, Bartlett and Kaiser are all varieties of which fruit?', 'Pear'),
('Food', 'Which product is advertised on TV with the slogan, “Once you pop you can’t stop”?', 'Pringles'),
('Food', 'What is the official national cheese of Greece?', 'Feta'),
('Food', 'Which variety of orange was named after a Japanese province?', 'Satsuma'),
('Food', 'Marzipan is made from which nuts?', 'Almonds'),
('Food', 'During brewing what is converted into alcohol?', 'Sugar'),
('Food', 'This chick pea pureé is flavoured with tahini and served as a dip?', 'Hummus'),
('Food', 'Grolsch lager is from which country?', 'Holland'),
('Food', 'This carbohydrate fruit is high in potassium?', 'Banana'),
('Food', 'What overtook coca-cola as the most well known brand name (in the world) in 1996?', 'McDonalds'),
('Food', 'The ''M'' in the McDonalds logo is what colour?', 'Yellow'),
('Food', 'Bacardi Rum''s logo features which creature?', 'Bat'),
('Food', 'An egg plant is also known as which vegetable?', 'Aubergine'),
('Food', 'What is a light round bun usually served hot?', 'Muffin'),
('Food', 'What is the plant that wards off vampires?', 'Garlic'),
('Food', 'The Teenage Mutant Ninja Turtles favourite food is?', 'Pizza'),
('Food', 'The main vegetable ingredient in the dish Borsht is what?', 'Beetroot'),
('Food', 'Sauerkraut is pickled what?', 'Cabbage'),
('Food', 'Chicory was a war time substitute for what drink?', 'Coffee'),
('Food', 'What vegetable is also known as zucchini in the USA?', 'Courgette'),
('Food', 'This fruit goes into the liqueur Kirsch?', 'Cherry'),
('Food', 'A bloomer is What type of food?', 'Bread'),
('Food', 'This type of milk is a basic ingredient in Thai cookery?', 'Coconut milk'),
('Food', 'What soft drink uses this slogan, "What''s the worst that could happen"?', 'Dr Pepper'),
('Food', 'Which is the fruit that contains the most calories?', 'Avocado pear'),
('Food', 'What are dried prunes?', 'Plums'),
('Food', 'The main cereal ingredient of flapkacks (Hudson Bars in USA)?', 'Oats'),
('Food', 'What is the correct spelling of a Cadbury Creame/Creem/Creme/Cream Egg?', 'Creme'),
('Food', 'What is Uganda''s staple crop, which each adult consumes over 3 times bodyweight annually?', 'Bananas'),
('Food', 'What''s lava bread?', 'Seaweed'),
('Food', 'What fruit grows on the blackthorn tree?', 'Sloe'),
('Food', 'Which two fruits are anagrams of each other?', 'Lemon & Melon'),
('Food', 'Homer Simpson drinks what brand of beer?', 'Duff'),
('Food', 'A crapulous person is full of what?', 'Acohol'),
('Food', 'What spanish drink consists of sweet red wine, lemonade or soda water and decorated with fruit?', 'Sangria'),
('Food', 'This spirit is the base for a Black Russian cocktail?', 'Vodka'),
('Food', 'What country is home to Grolsch lager?', 'Holland'),
('Food', 'A crapulous person is full of what?', 'Alcohol'),
('Food', 'What is the name of this hot red chilli pepper it is often dried and ground?', 'Cayenne Pepper'),
('Food', 'What''s colour of the inside of a pistachio nut?', 'Green'),
('Food', 'This is converted into alcohol during brewing?', 'Sugar'),
('Food', 'This herb is used to make a Pesto sauce?', 'Basil'),
('Food', 'When a wine is described as ''brut'' what does it mean about the taste?', 'Very Dry'),
('Food', 'The usual main meat ingredient of a Shish Kebab is?', 'Lamb'),
('Food', 'What do the brits call a Weenie?', 'A hot dog'),
('Food', 'The "D" where milk is processed?', 'Dairy'),
('Food', 'What spice gives piccalilli and curries its yellow colour?', 'Turmeric'),
('Food', 'Hash Browns are normally made from which vegetables?', 'Potatoes'),
('Food', 'Prunes stuffed with almonds are wrapped in what to make Devils on horseback?', 'Bacon'),
('Food', 'The main ingredient of a Paella is what?', 'Rice'),
('Food', 'The main ingredient of Sauerkraut is what?', 'Cabbage'),
('Food', 'This food has a name which means on a skewer?', 'Kebab'),
('Food', 'In a Mcdonald''s Big Mac how many pieces of bun are there?', 'Three'),
('Food', 'Oyster, Chestnut, or Shitaki are types of which vegetable?', 'Mushrooms'),
('Food', 'What is the only fruit named for its colour?', 'Orange'),
('Food', 'Traditionally at a fair ground what fruit would be covered with toffee?', 'Apple'),
('Food', 'This herb is used to flavour Pernod?', 'Aniseed'),
('Food', 'This milk is a basic ingredient in Thai cookery?', 'Coconut milk'),
('Geography', '300,000 Chinese troops invaded a country in February of 1979, what was the country?', 'Vietnam'),
('Geography', 'Worlds most remote weather station is located in what country?', 'Canada'),
('Geography', 'What European country was in an official state of emergency from 1933 until 1945?', 'Germany'),
('Geography', 'Which country lost over seventeen percent of its entire population in World War II?', 'Poland'),
('Geography', 'Which two countries share Victoria Falls?', 'Zimbabwe and Zambia'),
('Geography', 'Adolf Hitler was born in what country?', 'Austria'),
('Geography', 'In 1989, what country did the United States invade in what George Will dubbed "an act of hemispheric hygiene"?', 'Panama'),
('Geography', 'What country did Ion Iliescu take over after its previous president was arrested, tried and shot?', 'Romania'),
('Geography', 'What North American country enacted the War Powers Act to quell a separatist rebellion in 1970?', 'Canada'),
('Geography', 'Aruba maintains the strongest ties to what European country?', 'Netherlands'),
('Geography', 'Fireworks originated in what country?', 'China'),
('Geography', 'The Saturn V rocket was built by what country?', 'USA'),
('Geography', 'What European country uses its Latin Name, Helvetia, on its stamps?', 'Switzerland'),
('Geography', 'In which country was the World Wide Web invented?', 'Switzerland'),
('Geography', 'What is the name of the country that flew the first supersonic airliner in 1968 and had it crash in 1973?', 'The Soviet Union'),
('Geography', 'The Greek historian Herodotus dubbed what country "the gift of the Nile"?', 'Egypt'),
('Geography', 'In South America what is the largest country?', 'Brazil'),
('Geography', 'Japan sends the most what to Australia?', 'Tourists'),
('Geography', 'Which European country launched Europe''s first super high speed passenger train in 1981?', 'France'),
('Geography', 'Portugal is bordered by only want country, what is it?', 'Spain'),
('Geography', 'India ink was developed in what country?', 'China'),
('Geography', 'What country did 153 of the first 400 Nobel Prize-winning scientists call home?', 'The United States'),
('Geography', 'What country first came up with windmills?', 'Iran'),
('Geography', 'A patent on polyester was patented first in what country?', 'Briton'),
('Geography', 'The worlds first mid air collision took place over what country?', 'Austria'),
('Geography', 'Eddy Grant comes from what country?', 'Guyana'),
('Geography', 'Roxette came from which European country?', 'Sweden'),
('Geography', 'Celine Deion was born in what North American Country?', 'Canada'),
('Geography', 'What floral symbol do the country of Peru and the state of Kansas have in common?', 'The sunflower'),
('Geography', 'What country has a volcano called Okinawa?', 'Japan'),
('Geography', 'Lesotho is a southern African Kingdom surround by which country?', 'South Africa'),
('Geography', 'In what country can one find 40 species of lemurs?', 'Madagascar'),
('Geography', 'Which city is called Kapstad in Afrikaans?', 'Cape Town'),
('Geography', 'Which language apart from English is an official language of Canada?', 'French'),
('Geography', 'Okinawa is a volcano in which country?', 'Japan'),
('Geography', 'In which country is an Afghani a unit of currency?', 'Afghanistan'),
('Geography', 'Lesotho is a southern African Kingdom surrounded by which country?', 'South Africa'),
('Geography', 'Madagascar is off which coast of Africa?', 'East'),
('Geography', 'Antigua and Barbuda lie in which Sea?', 'Caribbean'),
('Geography', 'Ottawa is which country''s capital?', 'Canada'),
('Geography', 'The Chinese city of Beijing was previously known as what?', 'Peking'),
('Geography', 'Argentina''s east coast lies on which ocean?', 'Atlantic'),
('Geography', 'Which South American Canal joins the Atlantic to the Pacific oceans?', 'Panama'),
('Geography', 'What is the largest country in South America?', 'Brazil'),
('Geography', 'Edinburgh is in which country?', 'Scotland'),
('Geography', 'What is the Great Barrier Reef made from?', 'Coral'),
('Geography', 'Which Chinese landmark was viewed from space?', 'Great Wall of China'),
('Geography', 'For most of the 20th century ST. Petersburg has been named after which Soviet Hero?', 'Lenin'),
('Geography', 'Which US holiday state has the Everglades National Park?', 'Florida'),
('Geography', 'How was the Cote D''Ivoire previously known?', 'Ivory Coast'),
('Geography', 'Buckingham Palace is in which English City?', 'London'),
('Geography', 'The River Seine runs through which European capital city?', 'Paris'),
('Geography', 'The Victoria Falls are shared between Zimbabwe and which other country beginning with the same letter?', 'Zambia'),
('Geography', 'Which US state is famous for Disneyland and the film industry?', 'California'),
('Geography', 'The Channel Tunnel links England with which European country?', 'France'),
('Geography', 'What are the Islas Canarias in English?', 'Canary Islands'),
('Geography', 'Which Australian province has New at the beginning of its name?', 'South Wales'),
('Geography', 'Which tourist attraction is the only living structure visible from outer space?', 'The Great Barrier Reef'),
('Geography', 'Which House in London did the Queen Mother live?', 'Clarence House'),
('Geography', 'Which Scandinavian Capital Begins And Ends With The Same Letter?', 'Oslo'),
('Geography', 'What colour is the far left stripe on the French flag?', 'Blue'),
('Geography', 'How many stars are on the flag of New Zealand?', 'Four'),
('Geography', 'What aboriginal name is Ayers Rock also known as?', 'Uluru'),
('Geography', 'Which country is The Prado Art Museum?', 'Spain'),
('Geography', 'Where is the Louvre Art Museum?', 'Paris'),
('Geography', 'Which English city would you find Piccadilly Circus?', 'London'),
('Geography', 'Which one of England''s biggest shipping ports is famous for being the port that the Titanic left from?', 'Southampton'),
('Geography', 'This US state is the only one starting with ''H''?', 'Hawaii'),
('Geography', 'The city of Vienna stands on which river?', 'Danube'),
('Geography', 'The town of Tequila is in which country?', 'Mexico'),
('Geography', 'You will find the world famous Raffles Hotel in which country?', 'Singapore'),
('Geography', 'Stonehenge is in which English county?', 'Wiltshire'),
('Geography', 'Which Country produces the world''s best cigars?', 'Cuba'),
('Geography', 'The official language of Austria is what?', 'German'),
('Geography', 'Acapulco is in which country?', 'Mexico'),
('Geography', 'This City has the oldest Metro System in the world?', 'London'),
('Geography', 'Which country is the maple leaf the national symbol?', 'Canada'),
('Zoology', 'What kind of animal is the emblem of the US republican political party?', 'Elephant'),
('Zoology', 'What color is an ocelot?', 'Yellow with black markings'),
('Zoology', 'Which type of animals have more teeth, reptiles or mammals?', 'Mammals'),
('Zoology', 'A cow normally has how many teats?', 'Four'),
('Zoology', 'What is the only venomous snake found in Britain?', 'Adder'),
('Zoology', 'What type of leaves does a Koala use for food?', 'Eucalyptus'),
('Zoology', 'What type of animal is the main source of food for a mole?', 'Earthworms'),
('Zoology', 'What is another name for a Guinea Pig?', 'Cavy'),
('Zoology', 'What kind of animals live in an apiary?', 'Bees'),
('Zoology', 'What was Tarzan''s Chimpanzee''s name?', 'Cheta'),
('Zoology', 'Celeste was the wife of which fictional animal?', 'Babar the Elephant'),
('Zoology', 'What were the names of the two bears that lived in Jellystone park?', 'Yogi and Boo Boo'),
('Zoology', 'What is the name for a collection of frogs?', 'Army'),
('Zoology', 'What kind of animal was "Gentle Ben" on the TV show?', 'A Bear'),
('Zoology', 'A female donkey is called a what?', 'Jenny'),
('Zoology', 'On a common lady bug, what color are the spots?', 'Black'),
('Zoology', 'Which subhuman primate is the most intelligent?', 'Chimpanzee'),
('Zoology', 'A mandrill is what type of creature?', 'Monkey'),
('Zoology', 'The most Asian elephants to be found in their natural habitat can be found in what country?', 'India'),
('Zoology', 'Which animal is the fastest, a hare, greyhound, or horse?', 'Hare'),
('Zoology', 'What type of animal is a Tasmanian Devil?', 'Marsupial'),
('Zoology', 'Which sense is the weakest sense in most primates?', 'Sense of Smell'),
('Zoology', 'Sika, fallow, and Roe, are what types of animal?', 'Deer'),
('Zoology', 'Animals living in what type of habitat are arboreal animals?', 'In or amongst trees'),
('Zoology', 'What type of animal produces gossamer?', 'Spider'),
('Zoology', 'What kind of animal is the source of mohair?', 'Angora Goat'),
('Zoology', 'What land mammal other than man has the longest lifespan?', 'Elephant'),
('Zoology', 'Lupus is the Latin name for what animal?', 'Wolf'),
('Zoology', 'Who was the British TV personality that presented the show Animal Magic?', 'Johnny Morris'),
('Zoology', 'Michael Bond created what famous bear?', 'Paddington Bear'),
('Zoology', 'Walt Disney''s famous deer was named what?', 'Bambi'),
('Zoology', 'A horse named Black Bess was ridden by who?', 'Dick Trupin'),
('Zoology', 'In the Lone Range, what was Tonto''s horse''s name?', 'Scout'),
('Zoology', 'What kind of animals were Chi Chi and An An?', 'Panda bears'),
('Zoology', 'In the Jungle Book, what kind of creature was Baloo?', 'A bear'),
('Zoology', 'How do bees communicate with each other?', 'Dancing'),
('Zoology', 'A stoat produces fur called what?', 'Ermine'),
('Zoology', 'What type of insect eats its mate after mating?', 'Preying Mantis'),
('Zoology', 'Coral and algae have what kind of relationship?', 'Symbiotic'),
('Zoology', 'What kind of animals don''t hunt or eat any meat?', 'Herbivore'),
('Zoology', 'What is the name of the largest land animal?', 'Elephant'),
('Zoology', 'When caterpillar changes into an adult butterfly what is the change called?', 'Metamorphous'),
('Zoology', 'The study of animals is given the name of what?', 'Zoology'),
('Zoology', 'What type of mammals fly using echolocation?', 'Bats'),
('Zoology', 'How many types of panda are there?', 'Two'),
('Zoology', 'The longest beetle in the world is how long?', 'Six inches'),
('Zoology', 'Animals without backbones are called what?', 'Invertebrates'),
('Zoology', 'An earthworm has how many hearts?', '5'),
('Zoology', 'A fluke is what kind of animal?', 'Worm'),
('Zoology', 'The spots on a plaice are what color?', 'Orange'),
('Zoology', 'An abalone is what kind of animal?', 'Marine snail'),
('Zoology', 'The study of birds eggs is called what?', 'Oology'),
('Zoology', 'What is the offspring of a mare and a male ass called?', 'A mule'),
('Zoology', 'On a rabbit where would you find a scut?', 'The tail'),
('Zoology', 'In Thailand, what is the sacred animal?', 'The white elephant'),
('Zoology', 'Alphabetically, what animal comes first in the Chinese horoscope?', 'Boar'),
('Zoology', 'Alphabetically, what animal comes last in the Chinese horoscope?', 'Tiger'),
('Zoology', 'What type of animal is the symbol of medicine?', 'Snake'),
('Zoology', 'Which type of semi aquatic animal is a lutra-lutra?', 'An Otter'),
('Zoology', 'What animals make a sound called nuzzing?', 'Camels'),
('Zoology', 'What animal is the symbol of long life in Korea?', 'The Deer'),
('Zoology', 'A Curry Comb is used on what type of creature?', 'Horse'),
('Zoology', 'The llama belongs to what family to what family of animals?', 'Camel'),
('Zoology', 'Eskimos call what kind of creature a nanook?', 'Polar Bear'),
('Zoology', 'Which animal has the longest lifespan in captivity?', 'Giant Tortoise'),
('Zoology', 'In Peru, what animal provides 50% of all the protein eatin?', 'The Guinea Pig'),
('Zoology', 'What animal pollinates banana plants in the wild?', 'Bats'),
('Zoology', 'A fennec is what type of animal?', 'A Desert Fox'),
('Zoology', 'What kind of creature always gives birth to same sex twins?', 'Armadillo'),
('Zoology', 'The Suidae family is made up of what animals?', 'Pigs'),
('Zoology', 'A markhor is what type of animal?', 'Wild goat'),
('Zoology', 'What type of insect has the best eyesight?', 'Dragonfly'),
('Zoology', 'What form was the Egyptian god Sobek?', 'Crocodile'),
('Zoology', 'A cow''s stomach has how many chambers?', '4'),
('Zoology', 'How many humps does an African camel have?', 'One'),
('Zoology', 'Who are the queen bee''s closest servants in a beehive?', 'Drones'),
('Zoology', 'What is the animal with the Latin name "syncerus caffer"?', 'Cape Buffalo'),
('Zoology', 'A Quagga is an extinct animal that was a distant cousin to which animal that exists today?', 'Zebra'),
('Zoology', 'What does a carpophagus animal feed on?', 'Fruit'),
('Zoology', 'Which animal has rectangular pupils?', 'Goat'),
('Zoology', 'What kind of animal mates only once for 12 hours and can sleep for three years?', 'Snail'),
('Zoology', 'Do mosquitoes have teeth?', 'yes'),
('Zoology', 'A typical mayfly lives for how many days?', 'One'),
('Zoology', 'What is a fox''s den called?', 'Earth'),
('Zoology', 'What is the only mammal that can''t jump?', 'Elephant'),
('Zoology', 'What bird can swim but can''t fly?', 'Penguin'),
('Zoology', 'Which Fred is the Daily Mail''s cartoon dog?', 'Fred Bassett'),
('Zoology', 'In Winnie the Pooh, what kind of animal is Eeyore?', 'Donkey'),
('Zoology', 'What type of creature is a Basilisk?', 'Lizard'),
('Zoology', 'What type of animal according to Beatrix Potter was Mr Jeremy Fisher?', 'Frog'),
('Zoology', 'Which animal appears first in the dictionary?', 'Aardvark'),
('Zoology', 'What is the name given to the young of a Kangaroo?', 'Joey'),
('Zoology', 'What creature was Will Smith''s codename in the movie Independence day?', 'Eagle'),
('Zoology', 'What is a Natterjack?', 'Toad'),
('Zoology', 'What is the smallest bird in the world?', 'Hummingbird'),
('Zoology', 'Which animals does Lupine relate to?', 'Wolves'),
('Zoology', 'Which extinct creature got its name from the portuguese for stupid?', 'Dodo'),
('Zoology', 'Daddy Long Legs is the common name for which fly?', 'Crane Fly'),
('Zoology', 'A Harlequin is what type of bird?', 'Duck'),
('Zoology', 'In the 19th Century what creatures were frequently used to bleed patients?', 'Leeches'),
('Zoology', 'What type of creature is a sidewinder?', 'Snake'),
('Zoology', 'To signal the end of the flood which bird brought back a twig to Noah?', 'Dove'),
('Zoology', 'Which animal is used on the Toys R Us logo?', 'Giraffe'),
('Zoology', 'What is the deadliest spider?', 'The Black Widow Spider'),
('Zoology', 'How many times can a bee sting?', 'Once'),
('Zoology', 'Which bug has the most legs?', 'Millipede'),
('Zoology', 'Can iguanas blink?', 'No'),
('Zoology', 'Which penguin dad likes to babysit?', 'Emporer Penguin'),
('Zoology', 'What are baby elephants called?', 'Calves'),
('Zoology', 'The staple diet of a Koala bear is what?', 'Eucalyptus Leaves'),
('Zoology', 'The World Wildlife Fund has which animal as it''s symbol?', 'Giant Panda'),
('Zoology', 'The cabbage moth is which colour?', 'Brown'),
('Zoology', 'I will fend off anyone bad, I am mans best friend?', 'Dog'),
('Zoology', 'My babies weigh less than apples, I eat bamboo?', 'Panda bear'),
('Zoology', 'Cashmere is sourced from which animal?', 'Goat'),
('Zoology', 'A cow sweats from which part of its body?', 'Nose'),
('Zoology', 'What is a large, clawed, marine crustacean?', 'Lobster'),
('Zoology', 'What type of creature''s a bustard?', 'Bird'),
('Zoology', 'What creature was Will Smith''s codename in the movie Independence day?', 'Eagle'),
('Zoology', 'A lepidopterist collects?', 'Butterflies & moths'),
('Zoology', 'Moby Dick was what color?', 'White'),
('Zoology', 'On the top of the Calcutta Cup what animal will you find?', 'Elephant'),
('Zoology', 'What''s a Natterjack?', 'A Toad'),
('Zoology', 'What''s the smallest bird in the world?', 'The Hummingbird'),
('Zoology', 'Scooby Doo is what kind of dog?', 'Great Dane'),
('Zoology', 'Which animals does Lupine relate to?', 'Wolves'),
('Zoology', 'This extinct creature got its name from the portuguese for stupid?', 'Dodo'),
('Zoology', 'An octopus has how many hearts?', '3'),
('Zoology', 'Fish get oxygen through which organ?', 'Gills'),
('Zoology', 'The Offspring of a male donkey and a female horse is called what?', 'A mule'),
('Zoology', 'This Flightless Bird lays the World''s largest Eggs?', 'Ostrich'),
('Zoology', 'What was it that Killed Cleopatra?', 'An asp'),
('Zoology', 'A whales breathing organs are called what?', 'Lungs'),
('Zoology', 'After mating which aptly named spider devours its partner?', 'The Black Widow'),
('Zoology', 'The dog fish is what type of fish?', 'A shark'),
('Zoology', 'To signal the end of the flood which bird brought back a twig to Noah?', 'The dove'),
('Zoology', 'A Saki is what type of animal?', 'A Monkey'),
('Zoology', 'What''s a Wessex Saddleback?', 'A Pig'),
('Zoology', 'A Harlequin is what type of bird?', 'A duck'),
('Zoology', 'A sidewinder is what type of creature?', 'A snake'),
('Music', 'What was Barry Manilow''s first No 1 single?', 'Mandy'),
('Music', 'Who has accumulated the most UK and US top ten albums and grossed most income from foreign touring?', 'Rolling Stones'),
('Music', 'Who teamed up with Barbra Streisand for tell Him?', 'Celine Dion'),
('Music', 'Which group were fronted by Jon Bon Jovi?', 'Bon Jovi'),
('Music', 'Which lady socked it to the Harper Valley PTA?', 'Jennie C Riley'),
('Music', 'In which year did Al Stewart''s Year Of The Cat make the charts?', '1977'),
('Music', 'Who was the first female with two UK million-selling singles?', 'Celine Dion'),
('Music', 'Which Canadian-born artist was the biggest-selling singles artist tin the UK in 1991?', 'Bryan Adams'),
('Music', 'Felix Cavaliere and Dino Danelli were in which group?', 'Rascals'),
('Music', 'Which day of the week did the Mamas a & Papas sing about?', 'Monday'),
('Music', 'Who was back in the Angels classic 60s NO 1?', 'My Boyfriend'),
('Music', 'Who did Celine Dion support in his Canadian tour in 1991?', 'Michael Bolton'),
('Music', 'What is the name of Whitney Houston''s daughter named after the baby''s father?', 'Bobbie'),
('Music', 'Who teamed up with Paul McCartney for ebony and Ivory?', 'Stevie Wonder'),
('Music', 'Were the Doobie Brothers actually brothers?', 'No'),
('Music', 'In 1978 how many weeks at No 1 were taken up by the Gibb family?', '28'),
('Music', 'What was Taylor Dayne''s first top ten hit?', 'Tell It To My Heart'),
('Music', 'Who is Leslie Sebastian Charles in chart terms?', 'Billy Ocean'),
('Music', 'What was the last No 1 in the 60s?', 'Someday We''ll Be Together'),
('Music', 'Who had a No 1 with Brand New Key?', 'Melanie'),
('Music', 'Who had a 1994 No 1 with I Swear?', 'All-4-One'),
('Music', 'Which UK guitarist co-produced Bob Dylan''s album Infidels?', 'Mark Knopfler'),
('Music', 'Which group wrote the songs for the movie Saturday Night Fever?', 'The Bee Gees'),
('Music', 'Who was Saving All My Love For You?', 'Whitney Houston'),
('Music', 'Who found himself Alone Again (Naturally)?', 'Gilbert O''Sullivan'),
('Music', 'Manhattan Skyline and Open Sesame were on which album?', 'Saturday Night Fever'),
('Music', '1996 was the year of long-staying hits. How manly No 1s were there?', 'Nine'),
('Music', 'Who made NO 1 with Sledgehammer?', 'Peter Gabriel'),
('Music', 'Which artist got Kangaroo in to the title of a top three hit?', 'Rolf Harris'),
('Music', 'What word was used to describe Peggy March?', 'Little'),
('Music', 'Which Barry had 70s chart success with Never Never Gonna Give You Up and Can''t Get Enough Of Your Love Babe?', 'White'),
('Music', 'On which Stevie Wonder album did he team up with Michael Jackson to sing Get It?', 'Characters'),
('Music', 'Vision Of Love was the first British top ten hit for which female superstar?', 'Mariah Carey'),
('Music', 'Under what name did Jefferson Airplane regroup at the top of the charts?', 'Starship'),
('Music', 'Which No 1 began, "Sunshine came softly through my window today"?', 'Sunshine Superman'),
('Music', 'Who recorded the album Stranger In Town?', 'Bob Serger'),
('Music', 'To a year, when did Heart first have a top ten hit?', '1976'),
('Music', 'How is Leslie Wundermann better known?', 'Taylor Dayne'),
('Music', 'Who sang I''m Leaving It Up To You with Dale?', 'Grace'),
('Music', 'Which band recorded the album The Joshua Tree?', 'U2'),
('Music', 'In the 70s who put a Message In A Bottle?', 'Police'),
('Music', 'Which band had a big hit with You Make Me Wanna?', 'Usher'),
('Music', 'Money For Nothing was an 80s NO 1 for which band?', 'Dire Straits'),
('Music', 'Which Dimension had a 60s smash with Aquarius?', '5th Dimension'),
('Music', 'Which US Boys band featured three members of the Wilson Family?', 'The Beach Boys'),
('Music', 'Keith Richards rocked on in which super group?', 'The Rolling Stones'),
('Music', 'Who was backed by The Shondells?', 'Tommy James'),
('Music', 'How many boys were there in The Pet Shop Boys?', 'Two'),
('Music', 'Who fronted The Heartbreakers?', 'Tom Petty'),
('Music', 'Which heavy metal group took the name of Dutch-born members guitarist Eddie and drummer Alex?', 'Van Halen'),
('Music', 'Which 60s icon was backed by The Band?', 'Bob Dylan'),
('Music', 'Which band included Phil Collins and Peter Gabriel?', 'Genesis'),
('Music', 'Mickey Dolenz was in which 60s sensation group?', 'The Monkees'),
('Music', 'In which state did Chicago get together?', 'Illinois'),
('Music', 'Which band produced the album Dark Side Of The Moon?', 'Pink Floyd'),
('Music', 'Which group flew into the Hotel California?', 'The Eagles'),
('Music', 'R.E.M. cut the No 1 album Out Of what?', 'Time'),
('Music', 'Which band recorded the album Parallel Lines?', 'Blondie'),
('Music', 'Which band sang I want to Know What Love Is?', 'Foreigner'),
('Music', 'How many brothers were in the original Jackson family line up?', 'Five'),
('Music', 'Tusk was a best-selling album for which band?', 'Fleetwood Mac'),
('Music', 'What did the letter O stand for in ELO?', 'Orchestra'),
('Music', 'Whose hits include Bad Moon Rising and Green River?', 'Creedence Clearwater Revival'),
('Music', 'Which all time great band featured Harrison and Starkey?', 'The Beatles'),
('Music', 'This refers to chanted or spoken rhyming lyrics often used in hip hop music?', 'Rapping'),
('Music', 'Which member of Take That shares his surname with a fruit?', 'Jason Orange'),
('Music', 'What is the minimum number of musicians a band must have to be considered a "big band"?', 'Ten'),
('Music', 'What musical instrument''s sales escalated from 228,000 in 1950 to 2.3 million in 1971?', 'The guitar'),
('Music', 'What 1976 chart-topping song did Barry Manilow sing, but not write?', 'I Write the Songs'),
('Music', 'What does the Italian musical term adagio mean?', 'Slow'),
('Music', 'Who was the top-selling album artist of the 1970''s according to Billboard?', 'Elton John'),
('Music', 'What''s the only group to claim two of the top ten best-selling singles of the 1970''s?', 'The Bee Gees'),
('Music', 'Who was the first country artist to sell over 10 million copies of an album?', 'Garth Brooks'),
('Music', 'What band is named after a scuplture in Seattle that hums in the wind?', 'Soundgarden'),
('Music', 'What two Frank Sinatra hits were tops for U.S. karaoke singers in 1993?', 'New York, New York and My Way'),
('Music', 'What stringed symphonic instrument has a pedestal and a crown?', 'The Harp'),
('Music', 'What studio did the Beatles use to record 191 songs?', 'Abby Road'),
('Music', 'What jazz musician got his nickname by shortening "Satchel Mouth"?', 'Louis Armstrong'),
('Music', 'What jazz trumpeter was dubbed the "Prince of Darkness"?', 'Miles Davis'),
('Music', 'What did Def Leppard drummer Rick Allen lose in a 1984 auto accident?', 'An arm'),
('Music', 'What Southampton junior high school musical was cancelled in 1994 when Shinnecock Indians objected to the " Ug-a-wug" song?', 'Peter Pan'),
('Music', 'What classical conductor won posthumous Grammy Awards in 1991, 1992, and 1993?', 'Leonard Bernstein'),
('Music', 'Who''s "Monk" to jazz buffs?', 'Thelonious Monk'),
('Music', 'What California group waited 22 years to score their first chart-toping single since 1966?', 'The Beach Boys'),
('Music', 'What city''s opera house does " The Phantom of the Opera" prowl?', 'Paris'),
('Music', 'Who scored his first platinum album since 1978 with " The Icon Is Love " in 1994?', 'Barry White'),
('Music', 'What Michael Jackson album spawned five chart-topping singles?', 'Bad'),
('Music', 'What trumpeter became the oldest person ever to score a chart-topping single, in 1964?', 'Louis Armstrong'),
('Music', 'What rock star was trying to bite the head off a bat in concert when the bat decided to bite back?', 'Ozzy Osbourne'),
('Music', 'What Shania Twain recording became the best-selling country music album ever by a female artist, in 1996?', 'The Woman in Me'),
('Music', 'What patriotic song was originally titled "The Defense of Fort McHenry?', 'The Star Spangled Banner'),
('Music', 'Who''s waxed more gold and platinum albums than any other solo female artist?', 'Barbara Streisand'),
('Music', 'What singer for a 70''s British rock quartet changed his name from Frederick Bulsara?', 'Freddie Mercury'),
('Music', 'What rock''n''roll singer is memorialized by a eight-foot bronze statue in Lubbock, Texas?', 'Buddy Holly'),
('Music', 'What Woody Guthrie song goes "From California to the New York island / From the redwood forest to the Gulf Stream waters"?', 'This Land is Your Land'),
('Music', 'What Pink Floyd song was banned by the South African government after it became an anthem for black school children?', 'Another Brick in the Wall'),
('Music', 'What were the two most popular rock operas of 1969?', 'Hair and Tommy'),
('Music', 'What are the two most common unbowed stringed instruments found in a symphony orchestra?', 'The Harp and the Piano'),
('Music', 'What legendary soul singer wrecked his Corvette the first time he drove it?', 'Ray Charles'),
('Music', 'What tenor received a record 165 curtain calls at a Berlin opera house in 1988?', 'Luciano Pavarotti'),
('Music', 'What Beatles single lasted longest on the charts, at 19 weeks?', 'Hey Jude'),
('Music', 'What Broadway musical revival did Lou Diamond Philips refuse to shave the top of his head for, in 1996?', 'The King and I'),
('Music', 'Who appeared on the cover of Seventeen magazine before selling over 11 million copies of her debut album?', 'Whitney Houston'),
('Music', 'Who''d never been farther east than Montana when he wrote Proud Mary?', 'John Fogarty'),
('Music', 'What Kiss star sported the longest tongue in rock?', 'Gene Simmons'),
('Music', 'What Rodgers and Hammerstein show is the most often-performed musical in U.S. high schools?', 'Oklahoma!'),
('Music', 'What genre did Ice Cube define as "the network newscast black people never had"?', 'Rap'),
('Music', 'What 1865 Wagner opera opens on a ship?', 'Tristan and Isolde'),
('Music', 'What R&B vocal quartet titled its third album II in 1994?', 'Boyz II Men'),
('Music', 'Who are the Three Tenors?', 'Jose Carreras, Placido Domingo, Luciano Pavarotti'),
('Music', 'How many birthday candles were Cher, Dolly Parton and Sylivester Stallone each obliged to blow out in 1996?', 'Fifty'),
('Music', 'What bankrupt Las Vegas crooner spent $75,000 to refurbish his pet penguins'' pond?', 'Wayne Newton'),
('Music', 'What hard-drinking country legend explains his bumpy life in the book I Lived to Tell It All?', 'George Jones'),
('Music', 'Whose pop parody career includes the hits Addicted to Spuds, My Bologna and Eat It?', 'Wierd Al Yankovic''s'),
('Music', 'What bandleader became the first jazz musician to get an honorary degree from Columbia University, in 1973?', 'Duke Ellington'),
('Music', 'What female singer scored 14 million-selling singles between 1967 and 1973?', 'Aretha Franklin'),
('Music', 'Who was the first female artist to debut on the Billboard album chart at Number One?', 'Whitney Houston'),
('Music', 'What was the nickname of jazzman John Birks Gillespie?', 'Dizzy'),
('Music', 'Which of the inmates who heard Johnny Cash''s 1958 San Quentin concert became the biggest country music star?', 'Merle Haggard'),
('Music', 'What mother and child spent years in Nashville shopping demos they''d recorded on a $30 cassette recorder?', 'The Judds'),
('Music', 'What 15-year-old rock icon-to-be was grounded for the whole summer after sneaking out to her first concert, to see David Bowie?', 'Madonna'),
('Music', 'What Jackson actually had a million-selling LP called Let''s Get Serious?', 'Jermaine Jackson'),
('Music', 'What Sinatra signature tune became Elvis Presley''s best-selling posthumous hit?', 'My Way'),
('Music', 'What song-writing duo''s hits made it to Broadway in the show Smokey Joe''s Cafe?', 'Leiber and Stoller'),
('Music', 'How many Grammy Awards did Lawrence Welk garner during his 50-year career?', 'Zero'),
('Music', 'What jazz musician got his nickname by shortening "Satchel Mouth"?', 'Louis Armstrong'),
('Music', 'What rocker Darius Rucker''s stage name?', 'Hootie'),
('Music', 'What British group got its name from the title of a 1950 Muddy Waters song?', 'The Rolling Stones'),
('Music', 'Who was the youngest person to have a chart-topping solo single, in 1970?', 'Michael Jackson'),
('Music', 'What German playwright penned the lyrics to Mack the Knife and Alabama Song?', 'Bertholt Brecht'),
('Music', 'What''s indicated by the word fine on a piece of sheet music?', 'The end'),
('Music', 'What grungeless Seattle band''s name is affectionately abbreviated "Pot USA"?', 'The Presidents of the United States'),
('Music', 'What question ends the Ira Gershwin lines: "I got rhythm / I got music / I got my man..."?', 'Who could ask for anything more?'),
('Music', 'What calypso singer founded the USA For Africa charity that recorded We Are the World?', 'Harry Belafonte'),
('Music', 'What group''s lead guitar player is known for his guitar amps with control knobs that go up to 11, "one more than 10"?', 'Spinal Tap'),
('Music', 'What was the best-selling album named after a city, in the 1970s?', 'Boston'),
('Music', 'What fellow Floridian did Jon Secada write and sing back-up for before going solo?', 'Gloria Estefan'),
('Music', 'What song includes the lines: "I''ve lived a life that''s full / I traveled each and ev''ry highway..."?', 'My Way'),
('Music', 'What Beatles song advises: "One thing I can tell you is you got to be free"?', 'Come Together'),
('Music', 'What TV host went gold with the CD Romantic Christmas?', 'John Tesh'),
('Music', 'What seven words complete the Purple Haze line: "Actin'' funny, but I don''t know why"?', 'Scuse me while I kiss the sky'),
('Music', 'Who adorned his last piano with 350 pounds of rhinestones?', 'Liberace'),
('Music', 'What did Melissa Etheridge title her first album after coming out of the closet?', 'Yes I Am'),
('Music', 'How many singles did Bruce Springsteen put atop Billboard charts in the 1980s?', 'Zero'),
('Music', 'What crooner''s mother warned him not to change his name to Frankie Satin?', 'Frank Snatra'),
('Music', 'Who sold part of his ownership of Beatles songs to Sony for $95 million in 1995?', 'Michael Jackson'),
('Music', 'Who''s responsible for the LPs Shamrocks and Champagne, Bubbles in the Wine and Pick-a-Polka?', 'Lawrence Welk'),
('Music', 'Who did Chuck Berry say "could play a guitar just like ringing a bell"?', 'Johnny B. Goode'),
('Music', 'What classical conductor won posthumous Grammy Awards in 1991,1992, and 1993?', 'Leonard Bernstein'),
('Music', 'What singer for a ''70s British rock quartet changed his name from Frederick Bulsara?', 'Freddie Mercury'),
('Music', 'What British duo''s works are referred to as the Savoy Operas?', 'Gilbert & Sullivan'),
('Music', 'What rock group is immortalized on Butt-head''s T-shirt?', 'AC/DC'),
('Music', 'What stringed symphonic instrument has a pedestal and a crown?', 'The harp'),
('Music', 'Who were Benn, Bjorn, Agnetha and Frida?', 'ABBA'),
('Music', 'What rock group''s only beardless member is Frank Beard?', 'ZZ Top'),
('Music', 'How many of Frank Sinatra''s collaborators on Duets and Duets II joined him in the studio?', 'Zero'),
('Music', 'What three words preceded "land that I love" in a 1938 Irving Berlin tune?', 'God bless America'),
('Music', 'What Georgia rockers resurrected Dan Rather''s mysterious 1986 mugging in their 1994 track, What''s the Frequency, Kenneth?', 'R.E.M.'),
('Music', 'What group''s early BBC performances went quadruple platinum within two months of their U.S. release in late 1994?', 'The Beatles'),
('Music', 'What Stephen Foster tune encourages racing enthusiasts to "bet on de bay"?', 'Camptown Races'),
('Music', 'What singer sent the punk band Rancid a naked photo along with a plea to sign with her record label?', 'Madonna'),
('Music', 'How many former Beatles had chart-topping singles from 1973 to 1974?', 'Four'),
('Music', 'What rock star did Lou Diamond Phillips'' wife leave him for?', 'Melissa Etheridge'),
('Music', 'What MTV twosome are known as "The Bad Boys" in Mexico?', 'Beavis and Butt-head'),
('Music', 'What did rapper Mohandas Dewese coolly change his name to?', 'Kool Moe Dee'),
('Music', 'How many songs from the Beatles'' Sgt. Pepper''s Lonely Hearts Club Band were released as singles?', 'Zero'),
('Music', 'What folk-rocker said he''d like Billy Dee Williams or Mickey Rooney to play him if his life story is filmed?', 'Bob Dylan'),
('Music', 'What was the only language beat writer Jack Kerouac spoke until the age of six?', 'French'),
('Music', 'What Italian wrote 32 operas between the ages of 18 and 30?', 'Gioacchino Rossini'),
('Music', 'What countdown deejay intones: "keep your feet to the ground, and keep reaching for the stars"?', 'Casey Kasem'),
('Music', 'What Shania Twain recording became the best-selling country music album ever by a female artist, in 1996?', 'The Woman in Me'),
('Music', 'What Elton John album became the first album to enter the charts at Number One, in 1975?', 'Captain Fantastic and the Brown Dirt Cowboy'),
('Music', 'What veteran British rock star explained: "I smash guitars because I like them"?', 'Pete Townshend'),
('Music', 'What Alanis Morissette debut album sold over ten million copies?', 'Jagged Little Pill'),
('Music', 'Who stomped off a 1995 Lollapalooza stage after a fan of her late husband threw a shotgun shell at her feet?', 'Courtney Love'),
('Music', 'What opera star sold more recordings in 1990 than all but Madonna and Elton John?', 'Luciano Pavarottti'),
('Music', 'What country star changed his first name from Randall to Hank?', 'Hank Williams Jr'),
('Music', 'What Bizet opera concerns a gal who dumps a soldier for a bullfighter?', 'Carmen'),
('Music', 'What late pun rocker did Debbie Gibson try to contact during a Halloween séance in 1988?', 'Sid Vicious'),
('Music', 'What songstress died before the release of her cross-over album Dreaming of You?', 'Selena'),
('Music', 'What composer was honored on the bicentennial of his death with a 180-disc compilation of all his works?', 'Wolfgang Amadeus Mozart'),
('Music', 'What 1976 and 1991 hit begins: "Is this the real life / Is this just fantasy"?', 'Bohemian Rhapsody'),
('Music', 'What did Def Leppard drummer Rick Allen lose in a 1984 auto accident?', 'An arm'),
('Music', 'What Allman Brothers anthem announces: "When it''s time to leave I hope you''ll understand"?', 'Ramblin'' Man'),
('Music', 'What British punks played to more fans in the first weekend of their 1996 "Filthy Lucre" tour than during their entire 1978 U.S. tour?', 'The Sex Pistols'),
('Music', 'What 23-year-old Tejano singer was murdered by her fan club president?', 'Selena'),
('Music', 'Which Mariah Carey and Boyz II Men song became the first to spend 16 weeks at No 1?', 'One Sweet Day'),
('Music', 'What type of train did Veteran Rod Stewart chart with?', 'Downtown Train'),
('Music', 'Who had hits with El Paso and Devil Woman?', 'Marty Robbins'),
('Music', 'Who co-wrote Fame with David Bowie?', 'John Lennon'),
('Music', 'What does the V stand for in SWV?', 'Voices'),
('Music', 'Victoria Principal sang All I Have To Do Is Dream with which Gibb?', 'Andy'),
('Music', 'Who recorded Macarena (bayside boys mix)?', 'Los Del Rio'),
('Music', 'Who reached No 1 with Unbelievable?', 'EMF'),
('Music', 'Which group had 80s hits with Hard To Say I''m Sorry and Look Away?', 'Chicago'),
('Music', 'What was the first No 1 single for Hall & Oates?', 'Rich Girl'),
('Music', 'Who was described as "a woman who pulled herself up by her bra straps?"', 'Madonna'),
('Music', 'Who hit the top ten with the Unskinny Bop?', 'Poison'),
('Music', 'What was Heart''s first No 1 hit?', 'These Dreams'),
('Music', 'Which Gibb brother is the eldest?', 'Barry'),
('Music', 'I''ll Be There For You was the theme to which hit TV show?', 'Friends'),
('Music', 'Which liquid product featured the hit Like A Prayer in its advertisement?', 'Pepsi'),
('Music', 'Which year was the title of Zager & Evans'' only No 1?', '2525'),
('Music', 'On what date did Elton John first sing his biggest-selling single in public?', 'September 6th, 1997'),
('Music', 'Which girl got Kiss into the singles top ten for the first time?', 'Beth'),
('Music', 'Who duetted with Peabo Bryson on Beauty and the Beast?', 'Celine Dion'),
('Music', 'Who knocked themselves off No 1 position with their follow up On Bended Knee?', 'Boyz II Men'),
('Music', 'On which label does Mariah Carey record?', 'Columbia'),
('Music', 'Who had a 1978 No 1 with Boogie Oogie Oogie?', 'A Taste Of Honey'),
('Music', 'Who wrote under the pseudonym Bernard Webb?', 'Paul McCartney'),
('Music', 'What kind of Bites provided Def Leppard with a No 1 single?', 'Love'),
('Music', 'Which country does Eddy Grant originate from?', 'Guyana'),
('Music', 'Which film revived the 70s song You Sexy Thing?', 'The Full Monty'),
('Music', 'Who had a No 1 hit with Here Comes the Hot Stepper?', 'Ini Kamoze'),
('Music', 'Who was the first John to have four solo No 1 hits?', 'Denver'),
('Music', 'Who wrote the song The Last Thing On My Mind?', 'Tom Paxton'),
('Music', 'What was Nirvana''s third album called?', 'In Utero'),
('Music', 'Who did Janet Jackson sing The Best things in Life Are Free with?', 'Luther Vandross'),
('Music', 'In which state did 2 Pac and Dr Dre find Love?', 'California'),
('Music', 'In which state did Kurt Cobain die(kill himself)?', 'Washington'),
('Music', 'What was Michael Jackson''s debut hit away from the Jackson 5?', 'Got To Be There'),
('Music', 'Which artist was the subject of a 1991 biography by Randy Taraborelli?', 'Michael Jackson'),
('Music', 'Which band was fronted by Courtney Love?', 'Hole'),
('Music', 'Who duetted on the 1993 hit I''ve Got You Under My Skin with Frank Sinatra?', 'Bono'),
('Music', 'Who had a giant hit with Nobody Knows?', 'The Tony Rich Project'),
('Music', 'Which label did Toni Braxton''s Un-Break My Heart appear on?', 'Arista'),
('Music', 'Who was the first female to reach 30 top ten hits?', 'Madonna'),
('Music', 'Which 60s No 1 began with the French national anthem?', 'All You Need Is Love'),
('Music', 'Which Club went to the Wild, Wild West?', 'The Escape Club'),
('Music', 'Which female vocalist was a member of the Eurythimics?', 'Annie Lennox'),
('Music', 'What was the first single of The Spice Girls?', 'Wannabe'),
('Music', 'What colour rain did prince sing about?', 'Purple'),
('Music', 'This Spandau Ballet hit reached No.1 in 1991?', 'Gold'),
('Music', 'What colour ''roses'' did Aqua sing about?', 'Red'),
('Music', 'Dido sang a song about this colour flag?', 'White Flag'),
('Music', 'The Kaiser Chiefs sang about what girl?', 'Ruby'),
('Music', 'What colour polka dot bikini was a great party hit?', 'Yellow'),
('Music', 'Alvin and the Chipmunks sang about what colour ''People Eater''?', 'Purple'),
('Music', 'UB40 & Bob Marley sang about what type of wine?', 'Red Red Wine'),
('Music', 'Billy Idol sang about this popular type of wedding?', 'White'),
('Music', 'Van Morrison sang about what ''Eyed Girl''?', 'Brown'),
('Music', 'What only happens when it''s raining according to Fleetwood Mac?', 'Thunder'),
('Music', 'According to many singers over the years ... What keep falling on their head?', 'Raindrops'),
('Music', 'What did it ''Rain'' according to the Weathergirls?', 'Men'),
('Music', 'What type of days and Mondays did the Carpenters sing about?', 'Rainy'),
('Music', 'What did Leo Sayer sing about that was ''in his heart''?', 'Thunder'),
('Music', 'What did Katrina And The Waves ''Walk On''?', 'Sunshine'),
('Music', 'What did Patrick Swayze say "She''s Like"?', 'The Wind'),
('Music', 'What was ''Up above the streets and houses, climbing high, which everyone could see smiling, over the sky''?', 'Rainbow'),
('Music', 'What did the sun always shine on according to A HA?', 'TV'),
('Music', 'What did Bette Midler have beneath her wings?', 'Wind'),
('Music', 'Which was the first Beatle to become a granddad?', 'Ringo Starr'),
('Music', 'Where did Mini Viva leave there heart?', 'Tokyo'),
('Music', 'Which song by the palindromic (read same in either direction) pop group Abba had a palindromic title?', 'SOS'),
('Music', 'Who had No 1 hits with West End Girls and It’s a Sin?', 'Pet Shop Boys'),
('Music', 'Which group recorded the Bond theme for The Living Daylights?', 'AHA'),
('Music', 'Which song sang by Queen contains the line, One dream one soul, one prize, one goal?', 'A Kind Of Magic'),
('Music', 'In 1977 this group had a hit with ''Hotel California''?', 'Eagles'),
('Music', 'In 1982 who had a hit with ''Pass the Dutchie''?', 'Musical Youth'),
('Music', 'In 1990 who was ''Doin'' the Do''?', 'Betty Boo'),
('Music', 'In 2004 what DJ showed us how to ''Cha Cha Slide''?', 'DJ Casper'),
('Music', 'Elton John''s first version of ''A Candle In The Wind'' was about whom?', 'Marilyn Monroe'),
('Music', 'In 1985 which group was on a ''Road To No Where''?', 'Talking Heads'),
('Music', 'This "King of Rock and Roll" liked you to love him tender!?', 'Elvis Presley'),
('Music', 'In Dire Straits song ''Money For Nothing'' what sort of oven were they singing about?', 'Microwave'),
('Music', 'Which British singer recorded "Somethin'' Stupid" as a duet in 2001 with Nicole Kidman?', 'Robbie Williams'),
('Music', 'The deep toned wind instrument native to Australia is called a what?', 'Didgeridoo'),
